DIM = 5 5 5
MASS = 100
PRIMITIVE_AXES = AUTO
BAND_LABELS = $\Gamma$ H P $\Gamma$ N
BAND = 0.0 0.0 0.0  -0.5 0.5 0.5  0.25 0.25 0.25  0.0 0.0 0.0  0.0 0.5 0.0
BAND_POINTS = 201
EIGENVECTORS = .FALSE.
FULL_FORCE_CONSTANTS = .TRUE.
READ_FORCE_CONSTANTS = .TRUE.
